# Generated by Django 2.2.2 on 2019-06-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190628_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lost_product',
            name='lostlocation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
