# Generated by Django 2.2.2 on 2019-07-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190630_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lost_product',
            options={'ordering': ['-updated']},
        ),
        migrations.AlterField(
            model_name='lost_product',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lost_product',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
